#!/usr/bin/env python3
"""Generate src/ref/filter_tables.h from the curves tools/ref/filter_measure.py
measured on reSID: per chip model, g = tan(pi f0 / fs) for every 11-bit fc and
k = 1/Q for every 4-bit resonance, both Q21. The 68030 builds the same tables
at start and computes the per-write coefficients from them."""
import math
import numpy as np
from scipy.interpolate import PchipInterpolator

FS = 25175000.0 / 512
F0_MAX = 20500.0          # tan() must stay below 4 for Q21 words


def load(model):
    d = np.loadtxt(f"tools/ref/filter_curve_{model}.txt")
    fc, f0, q0 = d[:, 0], d[:, 1], d[:, 2]
    f0 = np.minimum(np.maximum.accumulate(f0), F0_MAX)       # measurement noise must not make it non-monotone
    full = np.exp(PchipInterpolator(fc, np.log(f0))(np.arange(2048)))
    f0 = np.maximum.accumulate(full)
    k0 = 1.0 / np.interp(np.arange(2048), fc, q0)
    kr = 1.0 / np.maximum.accumulate(np.loadtxt(f"tools/ref/filter_q_{model}.txt")[:, 1])   # 1/Qratio
    return f0, k0, kr


out = ["/* Generated by tools/ref/gen_filter_tables.py from reSID measurements. Do not edit. */\n",
       "#ifndef FILTER_TABLES_H\n#define FILTER_TABLES_H\n\n"]
gs, k0s, krs = [], [], []
for model in ("6581", "8580"):
    f0, k0, kr = load(model)
    gs.append([int(round(math.tan(math.pi * x / FS) * (1 << 21))) for x in f0])
    k0s.append([int(round(x * (1 << 21))) for x in k0])
    krs.append([int(round(x * (1 << 21))) for x in kr])
out.append("static const uint32_t filter_g_q21[2][2048] = {\n")
for g in gs:
    out.append("{\n" + ",".join(f"{v}" + ("\n" if i % 12 == 11 else "") for i, v in enumerate(g)) + "\n},\n")
out.append("};\n\n/* g*g and g*k0 per fc, Q21: the products that do not depend on res */\nstatic const uint32_t filter_g2_q21[2][2048] = {\n")
for g_, in zip(gs):
    out.append("{\n" + ",".join(f"{(v * v + (1 << 20)) >> 21}" + ("\n" if i % 12 == 11 else "") for i, v in enumerate(g_)) + "\n},\n")
out.append("};\n\nstatic const uint32_t filter_gk0_q21[2][2048] = {\n")
for g_, k0_ in zip(gs, k0s):
    out.append("{\n" + ",".join(f"{(a * b + (1 << 20)) >> 21}" + ("\n" if i % 12 == 11 else "") for i, (a, b) in enumerate(zip(g_, k0_))) + "\n},\n")
out.append("};\n\n/* 1/m for m = 1 + i/256, Q24 (257 entries, linear interpolation) */\nstatic const uint32_t filter_recip_q24[257] = {\n"
           + ",".join(f"{int(round((1 << 24) / (1 + i / 256.0)))}" + ("\n" if i % 12 == 11 else "") for i in range(257)) + "\n};\n\n/* k = 1/Q at res 0, per fc */\nstatic const uint32_t filter_k0_q21[2][2048] = {\n")
for g in k0s:
    out.append("{\n" + ",".join(f"{v}" + ("\n" if i % 12 == 11 else "") for i, v in enumerate(g)) + "\n},\n")
out.append("};\n\n/* 1/Q ratio against res 0, per res (k = k0 * kr) */\nstatic const uint32_t filter_kr_q21[2][16] = {\n")
for k in krs:
    out.append("{" + ",".join(str(v) for v in k) + "},\n")
out.append("};\n\n#endif\n")
open("src/ref/filter_tables.h", "w").write("".join(out))
print("src/ref/filter_tables.h written")
