#!/usr/bin/env python3
"""Generate src/ref/filter_tables.h from the parameters tools/ref/filter_fit.py
fitted to reSID: per chip model and 11-bit fc, g = tan(pi f0 / fs), g*g, g*k0 and
k0 (Q21), the three outputs' gains and the low-pass share in the high-pass
output (gain / 2 as Q23 words, i.e. Q22), and per resonance kr (Q21). The
player carries the same tables (tools/player/gen_player_tables.c)."""
import math
import numpy as np
from scipy.interpolate import PchipInterpolator

FS = 25175000.0 / 512
F0_MAX = 20400.0          # tan() must stay below 4 for Q21 words
SUM_MAX = 1.99            # LP and HP together: wl + wleak is one Q23 word of gain / 2


def load(model):
    d = np.loadtxt(f"tools/ref/filter_fit_{model}.txt")
    # Where the filter is all but closed (the 8580 at fc 0) the fit has nothing to hold on to:
    # take the next row's shape and continue its cutoff downwards.
    for i in range(len(d) - 2, -1, -1):
        if d[i, 7] > 8.0:
            d[i, 2:7] = d[i + 1, 2:7]
            d[i, 1] = max(20.0, 2 * d[i + 1, 1] - d[i + 2, 1])
    fc = d[:, 0]
    x = np.arange(2048)
    f0 = np.minimum(np.maximum.accumulate(d[:, 1]), F0_MAX)       # fit noise must not make it non-monotone
    f0 = np.maximum.accumulate(np.exp(PchipInterpolator(fc, np.log(f0))(x)))
    k0 = np.interp(x, fc, d[:, 2])
    gl, gb, gh = (np.interp(x, fc, d[:, i]) for i in (3, 4, 5))
    leak = np.interp(x, fc, d[:, 6]) * gh                         # as the weight on the low-pass output
    leak = np.clip(leak, -SUM_MAX, SUM_MAX - gl)
    kr = np.loadtxt(f"tools/ref/filter_q_{model}.txt")[:, 1]
    return f0, k0, kr, gl, gb, gh, leak


def rows(values):
    return "{\n" + ",".join(f"{v}" + ("\n" if i % 12 == 11 else "") for i, v in enumerate(values)) + "\n},\n"


def table(name, ctype, per_model, comment=""):
    return (f"{comment}static const {ctype} {name}[2][{len(per_model[0])}] = {{\n"
            + "".join(rows(v) for v in per_model) + "};\n\n")


data = [load(m) for m in ("6581", "8580")]
q21 = lambda a: [int(round(v * (1 << 21))) for v in a]
q22 = lambda a: [int(round(v * (1 << 22))) for v in a]
g = [q21(np.tan(np.pi * d[0] / FS)) for d in data]
k0 = [q21(d[1]) for d in data]
out = ["/* Generated by tools/ref/gen_filter_tables.py from tools/ref/filter_fit_*.txt (reSID measurements). Do not edit. */\n",
       "#ifndef FILTER_TABLES_H\n#define FILTER_TABLES_H\n\n"]
out.append(table("filter_g_q21", "uint32_t", g))
out.append(table("filter_g2_q21", "uint32_t", [[(v * v + (1 << 20)) >> 21 for v in gm] for gm in g],
                 "/* g*g and g*k0 per fc, Q21: the products that do not depend on res */\n"))
out.append(table("filter_gk0_q21", "uint32_t", [[(a * b + (1 << 20)) >> 21 for a, b in zip(gm, km)] for gm, km in zip(g, k0)]))
out.append("/* 1/m for m = 1 + i/256, Q24 (257 entries, linear interpolation) */\nstatic const uint32_t filter_recip_q24[257] = {\n"
           + ",".join(f"{int(round((1 << 24) / (1 + i / 256.0)))}" + ("\n" if i % 12 == 11 else "") for i in range(257)) + "\n};\n\n")
out.append(table("filter_k0_q21", "uint32_t", k0, "/* k = 1/Q at res 0, per fc */\n"))
out.append("/* k ratio against res 0, per res (k = k0 * kr) */\nstatic const uint32_t filter_kr_q21[2][16] = {\n"
           + "".join("{" + ",".join(str(v) for v in q21(d[2])) + "},\n" for d in data) + "};\n\n")
out.append(table("filter_wl_q22", "int32_t", [q22(d[3] / 1) for d in data],
                 "/* the outputs' gains against a voice routed past the filter, per fc: gain / 2 as a Q23 word */\n"))
out.append(table("filter_wb_q22", "int32_t", [q22(d[4]) for d in data]))
out.append(table("filter_wh_q22", "int32_t", [q22(d[5]) for d in data]))
out.append(table("filter_wleak_q22", "int32_t", [q22(d[6]) for d in data],
                 "/* the low-pass share in the high-pass output, times its gain */\n"))
out.append("#endif\n")
open("src/ref/filter_tables.h", "w").write("".join(out))
print("src/ref/filter_tables.h written")
