#!/usr/bin/env python3
"""Generate the SID register traces used by the voice reference gate.

Writes tests/traces/voice_*.trace ("cycle reg value" lines, final "end N").
Deterministic: running it again reproduces the committed files.

  rand_*    random register traffic on all three voices (every waveform,
            combined waveforms, test, sync, ring, gate toggles, AD/SR changes
            including rate changes under a running envelope). These gate the
            reference bit-for-bit against reSID.
  filt_*    rand_* traffic plus random filter, resonance, routing, mode and volume
            writes; these gate the filter and mixer (DSP bit for bit, reSID by spectrum).
  adsr_bug  an envelope whose rate is lowered below the running counter
            (the ADSR delay bug), retriggered mid-decay, released at zero.
  noise     noise at every frequency decade, plus test-bit LFSR resets.
  tone_*    steady notes for the band-limiting gate (alias and level).
"""

import os
import random

OUT = os.path.join(os.path.dirname(__file__), "..", "..", "tests", "traces")


def save(name, events, end):
    events = sorted(events, key=lambda e: e[0])
    path = os.path.join(OUT, f"voice_{name}.trace")
    with open(path, "w", newline="\n") as f:
        f.write(f"# generated by tools/ref/make_voice_traces.py\n")
        for c, r, v in events:
            f.write(f"{c} {r} {v}\n")
        f.write(f"end {end}\n")


def freq_writes(t, voice, f):
    b = voice * 7
    return [(t, b + 0, f & 0xFF), (t, b + 1, f >> 8)]


def pw_writes(t, voice, pw):
    b = voice * 7
    return [(t, b + 2, pw & 0xFF), (t, b + 3, pw >> 8)]


def rand_trace(seed, cycles=600000):
    rnd = random.Random(seed)
    ev = []
    for v in range(3):
        b = v * 7
        ev += freq_writes(10 + v, v, rnd.randint(500, 40000))
        ev += pw_writes(10 + v, v, rnd.randint(0, 0xFFF))
        ev += [(12, b + 5, rnd.randint(0, 255)), (12, b + 6, rnd.randint(0, 255))]
        ev += [(20 + v, b + 4, 0x41 | (rnd.randint(0, 3) << 4 & 0xF0))]
    t = 100
    while t < cycles:
        t += int(rnd.expovariate(1 / 5000.0)) + 1
        v = rnd.randint(0, 2)
        b = v * 7
        k = rnd.random()
        if k < 0.25:
            f = int(2 ** rnd.uniform(4, 16)) & 0xFFFF
            ev += freq_writes(t, v, f)
        elif k < 0.35:
            ev += pw_writes(t, v, rnd.randint(0, 0xFFF))
        elif k < 0.60:
            wave = rnd.choice([0x10, 0x20, 0x40, 0x80, 0x30, 0x50, 0x60, 0x70,
                               0xC0, 0x90, 0xA0, 0xB0, 0xD0, 0xE0, 0xF0, 0x00])
            ctl = wave | rnd.choice([0, 0, 0, 1, 1, 1, 1])
            if rnd.random() < 0.15:
                ctl |= 0x02
            if rnd.random() < 0.15:
                ctl |= 0x04
            if rnd.random() < 0.04:
                ctl |= 0x08
            ev.append((t, b + 4, ctl))
        elif k < 0.80:
            ev.append((t, b + 5, rnd.randint(0, 255)))
        else:
            ev.append((t, b + 6, rnd.randint(0, 255)))
    return ev, cycles


def adsr_bug():
    ev = []
    ev += freq_writes(5, 0, 7493)
    ev += [(5, 5, 0x00), (5, 6, 0xA9)]
    ev.append((10, 4, 0x21))                  # saw, gate on, attack 2 ms
    ev.append((20000, 5, 0x0F))               # decay 24 s? long decay period
    ev.append((40000, 5, 0x00))               # decay period below the counter
    ev.append((60000, 4, 0x20))               # release
    ev.append((90000, 6, 0xA0))               # release rate lowered (bug path)
    ev.append((120000, 4, 0x21))              # retrigger mid-release
    ev.append((130000, 4, 0x20))              # release again, immediately
    ev.append((135000, 4, 0x21))
    ev.append((136000, 4, 0x20))
    ev.append((136200, 4, 0x21))              # attack/release flips within a frame
    ev.append((136210, 4, 0x20))
    ev.append((200000, 6, 0x00))              # fastest release, let it hit zero
    ev.append((300000, 4, 0x21))              # attack from zero (hold_zero)
    ev.append((310000, 5, 0x89))
    ev.append((400000, 5, 0x00))
    return ev, 500000


def noise():
    ev = []
    ev += [(5, 5, 0x00), (5, 6, 0xF0)]
    t = 10
    for f in (200, 1200, 5000, 16000, 40000, 65535):
        ev += freq_writes(t, 0, f)
        ev.append((t + 1, 4, 0x81))
        t += 80000
    ev.append((t, 4, 0x89))                   # test: LFSR reset countdown
    ev.append((t + 20000, 4, 0x81))
    ev.append((t + 60000, 4, 0x89))
    ev.append((t + 90000, 4, 0x81))
    ev.append((t + 91000, 4, 0x91))           # noise + triangle: LFSR lockup path
    ev.append((t + 100000, 4, 0x81))
    return ev, t + 200000


def sync_ring():
    ev = []
    for v in range(3):
        ev += [(5, v * 7 + 5, 0x00), (5, v * 7 + 6, 0xF0)]
    ev += freq_writes(10, 2, 3000)            # voice 3 is voice 1's sync/ring source
    ev += freq_writes(10, 0, 11000)
    ev.append((11, 4, 0x13))                  # voice 1: triangle, sync, gate
    ev.append((12, 18, 0x11))                 # voice 3: triangle, gate
    ev.append((100000, 4, 0x15))              # ring instead of sync
    ev.append((200000, 4, 0x17))              # both
    ev.append((300000, 4, 0x23))              # saw + sync
    ev += freq_writes(310000, 0, 29000)
    ev += freq_writes(320000, 2, 17000)
    ev.append((400000, 4, 0x43))              # pulse + sync
    ev += pw_writes(400001, 0, 0x400)
    ev += [(500000, 11, 0x43), (500000, 7 + 4, 0x43)]   # voice 2 synced by 1
    ev += freq_writes(500001, 1, 5000)
    ev.append((600000, 18, 0x07))             # voice 3 ring-modulated by voice 2, triangle off
    return ev, 700000


def tone(kind, f):
    ctl = {"saw": 0x21, "pulse": 0x41, "tri": 0x11}[kind]
    ev = []
    ev += [(5, 5, 0x00), (5, 6, 0xF0)]
    ev += freq_writes(6, 0, f)
    ev += pw_writes(6, 0, 0x800 if kind != "pulse" else 0x200)
    ev.append((20, 4, ctl))
    return ev, 560000


def dsp_trace(seed, cycles=500000):
    """Voice 0 only, waveforms 0 (none), triangle, saw, pulse, the test bit,
    every envelope/gate path: what the first DSP milestone implements."""
    rnd = random.Random(1000 + seed)
    ev = freq_writes(5, 0, rnd.randint(500, 40000)) + pw_writes(5, 0, rnd.randint(0, 0xFFF))
    ev += [(6, 5, rnd.randint(0, 255)), (6, 6, rnd.randint(0, 255)), (20, 4, 0x41)]
    t = 100
    while t < cycles:
        t += int(rnd.expovariate(1 / 4000.0)) + 1
        k = rnd.random()
        if k < 0.25:
            ev += freq_writes(t, 0, int(2 ** rnd.uniform(4, 16)) & 0xFFFF)
        elif k < 0.37:
            ev += pw_writes(t, 0, rnd.randint(0, 0xFFF))
        elif k < 0.67:
            ctl = rnd.choice([0x00, 0x10, 0x20, 0x40]) | rnd.choice([0, 1, 1, 1])
            if rnd.random() < 0.06:
                ctl |= 0x08
            ev.append((t, 4, ctl))
        elif k < 0.84:
            ev.append((t, 5, rnd.randint(0, 255)))
        else:
            ev.append((t, 6, rnd.randint(0, 255)))
    return ev, cycles


def dsp2_trace(seed, cycles=500000):
    """Voice 0 only, every waveform setting 0-15 (noise, combined waveforms,
    noise combinations), the test bit, ring and sync bits, every envelope path:
    what the second DSP milestone implements. Voices 2 and 3 stay idle."""
    rnd = random.Random(2000 + seed)
    ev = freq_writes(5, 0, rnd.randint(500, 40000)) + pw_writes(5, 0, rnd.randint(0, 0xFFF))
    ev += [(6, 5, rnd.randint(0, 255)), (6, 6, rnd.randint(0, 255)), (20, 4, 0x81)]
    t = 100
    while t < cycles:
        t += int(rnd.expovariate(1 / 3000.0)) + 1
        k = rnd.random()
        if k < 0.22:
            ev += freq_writes(t, 0, int(2 ** rnd.uniform(4, 16)) & 0xFFFF)
        elif k < 0.32:
            ev += pw_writes(t, 0, rnd.randint(0, 0xFFF))
        elif k < 0.72:
            ctl = (rnd.randint(0, 15) << 4) | rnd.choice([0, 1, 1, 1])
            if rnd.random() < 0.12:
                ctl |= 0x08
            if rnd.random() < 0.12:
                ctl |= 0x04
            if rnd.random() < 0.12:
                ctl |= 0x02
            ev.append((t, 4, ctl))
        elif k < 0.86:
            ev.append((t, 5, rnd.randint(0, 255)))
        else:
            ev.append((t, 6, rnd.randint(0, 255)))
    return ev, cycles


def filt_trace(seed, cycles=600000):
    """Voice traffic as rand_*, plus random filter and mixer registers ($15-$18):
    cutoff sweeps and jumps over all 2048 values, every resonance and routing,
    every mode combination (voice 3 off included) and volume steps."""
    rnd = random.Random(1000 + seed)
    ev, _ = rand_trace(seed, cycles)
    fc = rnd.randint(0, 2047)
    ev += [(5, 21, fc & 7), (5, 22, fc >> 3), (5, 23, (rnd.randint(0, 15) << 4) | rnd.randint(1, 7)),
           (5, 24, (rnd.choice([1, 2, 4, 3, 5, 6, 7, 1, 1]) << 4) | rnd.randint(8, 15))]
    t = 200
    while t < cycles:
        t += int(rnd.expovariate(1 / 6000.0)) + 1
        k = rnd.random()
        if k < 0.30:                     # cutoff sweep step
            fc = max(0, min(2047, fc + rnd.randint(-60, 60)))
            ev += [(t, 22, fc >> 3), (t + 1, 21, fc & 7)]
        elif k < 0.40:                   # cutoff jump
            fc = rnd.randint(0, 2047)
            ev += [(t, 21, fc & 7), (t, 22, fc >> 3)]
        elif k < 0.60:
            ev.append((t, 23, (rnd.randint(0, 15) << 4) | rnd.randint(0, 15)))
        elif k < 0.90:
            mode = rnd.randint(0, 15)
            ev.append((t, 24, (mode << 4) | rnd.randint(0, 15)))
        else:
            ev.append((t, 24, (rnd.choice([1, 2, 4, 5, 3]) << 4) | rnd.randint(0, 15)))
    return ev, cycles


def main():
    os.makedirs(OUT, exist_ok=True)
    for seed in range(1, 9):
        ev, end = rand_trace(seed)
        save(f"rand_{seed}", ev, end)
    for seed in range(1, 9):
        save(f"dsp_{seed}", *dsp_trace(seed))
    for seed in range(1, 11):
        save(f"dsp2_{seed}", *dsp2_trace(seed))
    for seed in range(1, 7):
        save(f"filt_{seed}", *filt_trace(seed))
    save("adsr_bug", *adsr_bug())
    save("noise", *noise())
    save("sync_ring", *sync_ring())
    # F register values: 110, 441, 1013, 2008 and 3801 Hz
    for kind in ("saw", "pulse", "tri"):
        for f in (1873, 7509, 17250, 34190, 64720):
            save(f"tone_{kind}_{f}", *tone(kind, f))


if __name__ == "__main__":
    main()
