/*
 * The tables the player carries, one binary per chip model.
 *
 *   gen_player_tables <resid_dir> <out dir>
 *
 * Writes sidtab_6581.bin, sidtab_8580.bin (big-endian longs) and sidtab.i (the
 * offsets): the DSP's configuration words and tables in the kernel's scaling
 * (docs/dsp-kernel.md, protocol.inc), exactly as tools/dsp/make_vec.c sends
 * them, and the filter tables the 68030 derives the coefficient words from
 * (src/m68k/filtcoef.s, sid_filter_coeffs() in src/ref/sid_ref.c).
 */
#include "sid_ref.h"
#include "filter_tables.h"

#include <stdio.h>
#include <string.h>

static FILE *out, *inc;
static long pos;

static void put(uint32_t v)
{
    fputc((int)(v >> 24) & 255, out); fputc((int)(v >> 16) & 255, out);
    fputc((int)(v >> 8) & 255, out); fputc((int)v & 255, out);
    pos += 4;
}

static void mark(const char *name) { if (inc) fprintf(inc, "%-16s equ     %ld\n", name, pos); }

int main(int argc, char **argv)
{
    static const int combined[4] = { 3, 5, 6, 7 };
    static const char *const wname[4] = { "SIDTAB_WAVE3", "SIDTAB_WAVE5", "SIDTAB_WAVE6", "SIDTAB_WAVE7" };
    char path[1024];
    int m, i, k;

    if (argc < 3) { fprintf(stderr, "usage: %s resid_dir out_dir\n", argv[0]); return 2; }
    if (sid_tables_init(argv[1])) return 1;
    snprintf(path, sizeof path, "%s/sidtab.i", argv[2]);
    inc = fopen(path, "w");
    if (!inc) { perror(path); return 1; }
    fprintf(inc, "; generated by tools/player/gen_player_tables.c; do not edit\n; byte offsets into sidtab_<model>.bin (longs)\n");
    for (m = 0; m < 2; m++) {
        int32_t cc, mk, fg;
        snprintf(path, sizeof path, "%s/sidtab_%s.bin", argv[2], m ? "8580" : "6581");
        out = fopen(path, "wb");
        if (!out) { perror(path); return 1; }
        pos = 0;
        sid_mix_config((sid_model_t)m, &cc, &mk, &fg);
        mark("SIDTAB_CONFIG");                  /* the seven DSP_CMD_CONFIG words */
        put((uint32_t)sid_wave_zero((sid_model_t)m)); put((uint32_t)sid_floating_ttl_start((sid_model_t)m));
        put((uint32_t)m); put((uint32_t)sid_shift_reset_start((sid_model_t)m));
        put((uint32_t)cc); put((uint32_t)mk); put((uint32_t)fg);
        mark("SIDTAB_RATE");
        for (i = 0; i < 16; i++) put(sid_tab_rate_period()[i]);
        mark("SIDTAB_SUST");
        for (i = 0; i < 16; i++) put(sid_tab_sustain_level()[i]);
        mark("SIDTAB_ENV");                     /* 512: envelope DAC << 13, exponential period */
        for (i = 0; i < 256; i++) {
            int per = i == 0xff ? 1 : i == 0x5d ? 2 : i == 0x36 ? 4 : i == 0x1a ? 8 : i == 0x0e ? 16 :
                      i == 0x06 ? 30 : i == 0 ? -1 : 0;
            put((uint32_t)sid_tab_env_dac((sid_model_t)m)[i] << 13);
            put((uint32_t)per & 0xffffff);
        }
        mark("SIDTAB_WAVEDAC");                 /* 4096: (wave DAC - zero) << 10 */
        for (i = 0; i < 4096; i++)
            put((uint32_t)(((int)sid_tab_wave_dac((sid_model_t)m)[i] - (int)sid_wave_zero((sid_model_t)m)) * 1024) & 0xffffff);
        for (k = 0; k < 4; k++) {
            mark(wname[k]);
            for (i = 0; i < 4096; i++) put(sid_tab_wave((sid_model_t)m, combined[k])[i]);
        }
        mark("SIDTAB_G");                       /* the filter: g, g*g, g*k0, k0 by fc (Q21) */
        for (i = 0; i < 2048; i++) put(filter_g_q21[m][i]);
        mark("SIDTAB_G2");
        for (i = 0; i < 2048; i++) put(filter_g2_q21[m][i]);
        mark("SIDTAB_GK0");
        for (i = 0; i < 2048; i++) put(filter_gk0_q21[m][i]);
        mark("SIDTAB_K0");
        for (i = 0; i < 2048; i++) put(filter_k0_q21[m][i]);
        mark("SIDTAB_KR");                      /* kr by res (Q21) */
        for (i = 0; i < 16; i++) put(filter_kr_q21[m][i]);
        mark("SIDTAB_RECIP");                   /* 257: 1/m for m in [1, 2], Q24 */
        for (i = 0; i < 257; i++) put(filter_recip_q24[i]);
        mark("SIDTAB_WL");                      /* the outputs' gains / 2 by fc (Q23 words) */
        for (i = 0; i < 2048; i++) put((uint32_t)filter_wl_q22[m][i]);
        mark("SIDTAB_WB");
        for (i = 0; i < 2048; i++) put((uint32_t)filter_wb_q22[m][i]);
        mark("SIDTAB_WH");
        for (i = 0; i < 2048; i++) put((uint32_t)filter_wh_q22[m][i]);
        mark("SIDTAB_WLEAK");
        for (i = 0; i < 2048; i++) put((uint32_t)filter_wleak_q22[m][i]);
        mark("SIDTAB_SIZE");
        fclose(out);
        fclose(inc);
        inc = NULL;
    }
    return 0;
}
