#!/usr/bin/env python3
"""Write the register trace of the release package's demo tune.

  make_demo_trace.py <out.trace>

About half a minute of original music ("cycle reg value" lines, final "end N",
the format of tests/traces): a filtered pulse bass with PWM, a chord arpeggio
and a saw lead with vibrato over Am F C G. tools/player/make_trace_sid.py turns
it into DEMO.SID, so the package has something to play that is not a
copyrighted tune and that the player is known to handle.
"""
import math
import sys

FRAME = 19656                   # PAL frame, cycles
CLOCK = 985248
STEP = 6                        # frames per 16th note
BAR = 16 * STEP
BARS = 16

NOTES = {"C": 0, "D": 2, "E": 4, "F": 5, "G": 7, "A": 9, "B": 11}


def freq(name, cents=0.0):
    """SID frequency register for a note such as 'A4'."""
    semis = NOTES[name[0]] + 12 * (int(name[1]) - 4) - 9      # from A4
    hz = 440.0 * 2 ** ((semis + cents / 100.0) / 12.0)
    return min(65535, round(hz * 16777216 / CLOCK))


# per bar: bass root, arpeggio notes, lead (eighth notes, None holds)
CHORDS = [
    ("A1", ["A3", "C4", "E4", "A4"], ["A4", None, "C5", "E5", None, "D5", "C5", None]),
    ("F1", ["A3", "C4", "F4", "A4"], ["A4", None, "C5", "F5", None, "E5", "C5", None]),
    ("C2", ["G3", "C4", "E4", "G4"], ["G4", None, "C5", "E5", None, "G5", "E5", None]),
    ("G1", ["G3", "B3", "D4", "G4"], ["D5", None, "B4", "G4", None, "B4", "D5", None]),
]
BASS_STEPS = [0, None, 0, 12, None, 0, 12, 0, 0, None, 0, 12, None, 0, 7, 12]   # semitones above the root


def main():
    events = []
    state = {}

    def put(frame, reg, value):
        """Queue a write unless the register already holds the value."""
        if state.get(reg) != value:
            state[reg] = value
            events.append((frame * FRAME + 20 + 12 * sum(1 for e in events if e[0] // FRAME == frame), reg, value))

    def note(frame, voice, f):
        put(frame, voice * 7 + 0, f & 255)
        put(frame, voice * 7 + 1, f >> 8)

    put(0, 5, 0x09); put(0, 6, 0xA8)            # bass: pulse
    put(0, 12, 0x0A); put(0, 13, 0x68)          # arpeggio: pulse
    put(0, 19, 0x29); put(0, 20, 0x8A)          # lead: saw
    put(0, 23, 0xA1)                            # resonance 10, voice 1 through the filter
    put(0, 24, 0x1F)                            # low-pass, volume 15
    put(0, 9, 0x00); put(0, 10, 0x08)           # arpeggio pulse width: square

    lead_freq = 0
    lead_age = 0
    for frame in range(BARS * BAR):
        bar, pos = divmod(frame, BAR)
        step, sub = divmod(pos, STEP)
        root, arp, lead = CHORDS[bar % 4]

        # bass: 16th-note pattern, gate off two frames before the next step
        semis = BASS_STEPS[step]
        if semis is not None:
            if sub == 0:
                note(frame, 0, freq(root, 100 * semis))
                put(frame, 4, 0x41)
            elif sub == STEP - 2:
                put(frame, 4, 0x40)
        pw = 0x800 + round(0x500 * math.sin(frame * 2 * math.pi / 173))
        put(frame, 2, pw & 255)
        put(frame, 3, pw >> 8)
        fc = 0x30 + round(0x28 * (1 - math.cos(frame * 2 * math.pi / (4 * BAR))) / 2) + (0x18 if sub < 2 and semis is not None else 0)
        put(frame, 22, fc)

        # arpeggio: a chord note every two frames, retriggered on the beat, from bar 2
        if bar >= 2:
            note(frame, 1, freq(arp[(frame // 2) % 4]))
            if pos % (4 * STEP) == 0:
                put(frame, 11, 0x41)
            elif pos % (4 * STEP) == 4 * STEP - 3:
                put(frame, 11, 0x40)

        # lead: eighth notes with vibrato once the note has settled, from bar 4
        if bar >= 4:
            eighth, esub = divmod(pos, 2 * STEP)
            if esub == 0 and lead[eighth] is not None:
                lead_name = lead[eighth]
                lead_age = 0
                put(frame, 18, 0x20)
            if esub == 1 and lead[eighth] is not None:
                put(frame, 18, 0x21)
            nxt = lead[(eighth + 1) % 8]
            if esub == 2 * STEP - 1 and nxt is not None:
                put(frame, 18, 0x20)
            if state.get(18) is not None:
                depth = min(1.0, max(0.0, (lead_age - 10) / 10.0)) * 18
                lead_freq = freq(lead_name, depth * math.sin(lead_age * 2 * math.pi / 8))
                note(frame, 2, lead_freq)
                lead_age += 1

        # fade out over the last bar
        left = BARS * BAR - frame
        if left <= 60:
            put(frame, 24, 0x10 | (left // 4))

    end = BARS * BAR
    for reg in (4, 11, 18):
        put(end, reg, 0)
    put(end, 24, 0)
    with open(sys.argv[1], "w", newline="\n") as f:
        f.write("# generated by tools/player/make_demo_trace.py\n")
        for c, r, v in events:
            f.write(f"{c} {r} {v}\n")
        f.write(f"end {(end + 1) * FRAME}\n")


if __name__ == "__main__":
    main()
