#!/usr/bin/env python3
"""Expand src/dsp/sid.asm.in into the DSP kernel source (SID.ASM).

The DSP56001 has no register-plus-immediate-offset addressing, so a routine
that works on "the current voice" would pay a pointer set-up, a pipeline nop
and an indexed move for every variable. Instead the kernel's per-voice code is
written once in the template and instantiated three times with absolute
addresses, which is what the hot loops need anyway.

Template conventions:

  ;@equates                 replaced by the per-voice variable equates
  ;@voice ... ;@endvoice    the text between is instantiated for voices 0, 1, 2
                            (voice v is hard-synced and ring-modulated by v-1
                            and syncs v+1)
  S_NAME                    this voice's variable      -> V<v>_NAME
  SRC_NAME                  the sync/ring source voice -> V<(v+2)%3>_NAME
  DST_NAME                  the voice this one syncs   -> V<(v+1)%3>_NAME
  @V@                       the voice number
  @D@                       the number of the voice this one syncs (label_@D@)
  any label defined in a voice section gets the suffix _<v>, in every voice
  section (there are several: the frame's per-voice code is laid out phase by
  phase in internal P memory, the rest follows outside)
"""

import re
import sys

# Voice variable layout. Everything a frame touches lives at short addresses
# ($10-$3f, 16 words per voice) so that every access is one word and can ride
# on an ALU instruction as a parallel move: HOTX in X memory, HOTY at the same
# addresses in Y memory (S_ACC/S_ACCF form one 48-bit L: word). The variables
# only register writes and rare paths touch are in Y memory behind them.
HOTX = ["ACC", "REM", "FREQE", "THR", "WH", "ENVDAC", "OUT", "PW", "WAVEOUT",
        "BLCNT", "WAVEFORM", "TEST", "MSB", None, "RING", "SYNC"]       # None: a spare word (globals below)
HOTY = ["ACCF", "EH", "RATEPER", "CREF", "EXPREM", "EXPPER", "ENVP", "SUSP",
        "STATE", "PIPE", "HOLD", "RATECNT", "NOISE", "SR"]     # two spare words per voice hold globals
COLD = ["TTL", "NEXT", "ATTACK", "DECAY", "RELEASE", "GATE", "SRRESET", "TMPA",
        "TMPB", "TMPE", "WJ", "WF", "PULSE", "FREQ", "BLD", "BASEWH"]
X_SPARE = ["G_EPS13", "K_400", "G_BLHIT"]                    # the voices' spare X words, by voice
HSIZE = 16
CSIZE = len(COLD)
HBASE = 0x10
CBASE = 0x40        # in Y memory

LABEL_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*):", re.M)


def equates():
    assert len(HOTX) <= HSIZE and len(HOTY) <= HSIZE - 2
    assert HBASE + 3 * HSIZE <= 0x40, "hot variables must stay short-addressable"
    names = [n for n in HOTX if n]
    assert not (set(names) & set(HOTY)) and not ((set(names) | set(HOTY)) & set(COLD))
    assert CBASE + 3 * CSIZE <= 0x70, "the cold variables end below the band-limiting scratch (Y $70)"
    lines = ["; per-voice variables (generated by tools/dsp/gen_sid_asm.py)",
             f"HSIZE           equ     {HSIZE}", f"CSIZE           equ     {CSIZE}"]
    for v in range(3):
        lines.append(f"V{v}_BLREC     equ     ${0x5e + v:02x}      ; X: conservative edge-countdown reciprocal")
        lines.append(f"V{v}_BLWC      equ     ${0x64 + v:02x}      ; X: an edge at this distance (waveform index) or beyond is outside its window")
        lines.append(f"V{v}_NEDGE     equ     ${0x61 + v:02x}      ; X: the first noise edge not yet applied (noise bit off)")
        for i, name in enumerate(HOTX):
            if name:
                lines.append(f"V{v}_{name:<9} equ     ${HBASE + v * HSIZE + i:02x}      ; X short")
            else:
                lines.append(f"{X_SPARE[v]:<12} equ     ${HBASE + v * HSIZE + i:02x}      ; X short (global)")
        for i, name in enumerate(HOTY):
            lines.append(f"V{v}_{name:<9} equ     ${HBASE + v * HSIZE + i:02x}      ; Y short")
        for i, name in enumerate(COLD):
            lines.append(f"V{v}_{name:<9} equ     ${CBASE + v * CSIZE + i:02x}      ; Y")
    return "\n".join(lines) + "\n"


def instantiate(text, v, labels):
    s, d = (v + 2) % 3, (v + 1) % 3
    for lab in labels:
        text = re.sub(rf"\b{lab}\b", f"{lab}_{v}", text)
    text = re.sub(r"\bSRC_([A-Z0-9]+)\b", lambda m: f"V{s}_{m.group(1)}", text)
    text = re.sub(r"\bDST_([A-Z0-9]+)\b", lambda m: f"V{d}_{m.group(1)}", text)
    text = re.sub(r"\bS_([A-Z0-9]+)\b", lambda m: f"V{v}_{m.group(1)}", text)
    return text.replace("@V@", str(v)).replace("@D@", str(d))


def main():
    src = open(sys.argv[1]).read()
    # Labels defined in any voice section are per voice everywhere in voice sections
    # (the sections are spread over the file: the frame's hot code sits in internal P).
    voice_text = "\n".join(re.findall(r"^;@voice\n(.*?)^;@endvoice", src, re.M | re.S))
    labels = sorted(set(LABEL_RE.findall(voice_text)), key=len, reverse=True)
    out = []
    in_voice = False
    block = []
    for line in src.splitlines():
        t = line.strip()
        if t == ";@equates":
            out.append(equates())
        elif t == ";@voice":
            in_voice, block = True, []
        elif t == ";@endvoice":
            text = "\n".join(block) + "\n"
            for v in range(3):
                out.append(f";;;; ---- voice {v} ----")
                out.append(instantiate(text, v, labels))
            in_voice = False
        elif in_voice:
            block.append(line)
        else:
            out.append(line)
    open(sys.argv[2], "w", newline="\r\n").write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
