#!/usr/bin/env python3
"""Expand src/dsp/sid.asm.in into the DSP kernel source (SID.ASM).

The DSP56001 has no register-plus-immediate-offset addressing, so a routine
that works on "the current voice" would pay a pointer set-up, a pipeline nop
and an indexed move for every variable. Instead the kernel's per-voice code is
written once in the template and instantiated three times with absolute
addresses, which is what the hot loops need anyway.

Template conventions:

  ;@equates                 replaced by the per-voice variable equates
  ;@voice ... ;@endvoice    the text between is instantiated for voices 0, 1, 2
                            (voice v is hard-synced and ring-modulated by v-1
                            and syncs v+1)
  S_NAME                    this voice's variable      -> V<v>_NAME
  SRC_NAME                  the sync/ring source voice -> V<(v+2)%3>_NAME
  DST_NAME                  the voice this one syncs   -> V<(v+1)%3>_NAME
  @V@                       the voice number
  any label defined in a voice section gets the suffix _<v>
"""

import re
import sys

# Voice variable layout inside a voice block (VSIZE words per voice).
VARS = ["ACC", "FREQ", "PW", "PULSE", "WAVEFORM", "TEST", "WAVEOUT", "TTL",
        "RATECNT", "RATEPER", "EXPCNT", "EXPPER", "ENVCNT", "HOLD", "STATE",
        "NEXT", "PIPE", "ATTACK", "DECAY", "SUSTAIN", "RELEASE", "GATE", "SR",
        "SRRESET", "NOISE", "RING", "TMPC", "MSB", "SYNC", "DELTA", "SHIFTPER",
        "TMPDT", "TMPSTEP", "TMPA", "TMPB", "OUT", "PW12"]
VSIZE = 41
VBASE = 0x10

LABEL_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*):", re.M)


def equates():
    lines = ["; per-voice variables (generated by tools/dsp/gen_sid_asm.py)",
             f"VBASE           equ     ${VBASE:02x}", f"VSIZE           equ     ${VSIZE:02x}"]
    for v in range(3):
        for i, name in enumerate(VARS):
            lines.append(f"V{v}_{name:<9} equ     ${VBASE + v * VSIZE + i:02x}")
    assert len(VARS) <= VSIZE
    return "\n".join(lines) + "\n"


def instantiate(text, v):
    s, d = (v + 2) % 3, (v + 1) % 3
    labels = sorted(set(LABEL_RE.findall(text)), key=len, reverse=True)
    for lab in labels:
        text = re.sub(rf"\b{lab}\b", f"{lab}_{v}", text)
    text = re.sub(r"\bSRC_([A-Z0-9]+)\b", lambda m: f"V{s}_{m.group(1)}", text)
    text = re.sub(r"\bDST_([A-Z0-9]+)\b", lambda m: f"V{d}_{m.group(1)}", text)
    text = re.sub(r"\bS_([A-Z0-9]+)\b", lambda m: f"V{v}_{m.group(1)}", text)
    text = re.sub(r"x:<(V\d_)", r"x:\1", text)      # voice variables are not all short-addressable
    return text.replace("@V@", str(v))


def main():
    src = open(sys.argv[1]).read()
    out = []
    in_voice = False
    block = []
    for line in src.splitlines():
        t = line.strip()
        if t == ";@equates":
            out.append(equates())
        elif t == ";@voice":
            in_voice, block = True, []
        elif t == ";@endvoice":
            text = "\n".join(block) + "\n"
            for v in range(3):
                out.append(f";;;; ---- voice {v} ----")
                out.append(instantiate(text, v))
            in_voice = False
        elif in_voice:
            block.append(line)
        else:
            out.append(line)
    open(sys.argv[2], "w", newline="\r\n").write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
