/*
 * Turn a register trace into a DSP test vector and the expected output.
 *
 *   make_vec <6581|8580> <trace> <resid_dir> <vec.i> <expected.txt>
 *
 * vec.i is an m68k include for tools/dsp/voicetest.s: the tables the DSP needs
 * (rate periods, sustain levels, envelope and wave DAC in the kernel's scaling), the chip constants,
 * the frame count, and the register writes tagged with the frame they are
 * applied before (the same rule as ref_run: a write belongs to the frame whose
 * cycle range contains it). expected.txt has the reference model's voice 0
 * three voice `naive` outputs and the chip output (`mix`), four integers per frame.
 */
#include "sid_ref.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct { long long cycle; unsigned reg, value; } write_t;

static int read_trace(const char *path, write_t **out, size_t *count, long long *end)
{
    FILE *f = fopen(path, "r");
    char line[256];
    size_t cap = 1024, n = 0;
    write_t *w = malloc(cap * sizeof *w);

    *end = 0;
    if (!f) { perror(path); return -1; }
    while (fgets(line, sizeof line, f)) {
        char *p = line;
        long long c;
        int r, v;
        while (*p == ' ' || *p == '\t') ++p;
        if (*p == '#' || *p == '\n' || *p == 0) continue;
        if (!strncmp(p, "end", 3)) { *end = strtoll(p + 3, NULL, 0); continue; }
        if (sscanf(p, "%lli %i %i", &c, &r, &v) == 3) {
            if (n == cap) { cap *= 2; w = realloc(w, cap * sizeof *w); }
            w[n].cycle = c; w[n].reg = (unsigned)r; w[n].value = (unsigned)v;
            n++;
        }
    }
    fclose(f);
    *out = w;
    *count = n;
    return *end > 0 ? 0 : -1;
}

static void table(FILE *f, const char *label, const unsigned *v, int n)
{
    int i;
    fprintf(f, "%s:\n", label);
    for (i = 0; i < n; i += 8) {
        int j;
        fprintf(f, "        dc.l    ");
        for (j = 0; j < 8 && i + j < n; j++)
            fprintf(f, "%s%u", j ? "," : "", v[i + j]);
        fputc('\n', f);
    }
}

int main(int argc, char **argv)
{
    sid_ref_t s;
    sid_frame_t fr;
    write_t *w;
    size_t nw, wi = 0, k;
    long long end, c = 0;
    long nframes = 0;
    sid_model_t model;
    unsigned tmp[4096];
    FILE *vec, *expf;
    int i;
    long frame;

    if (argc < 6) {
        fprintf(stderr, "usage: %s 6581|8580 trace resid_dir vec.i expected.txt\n", argv[0]);
        return 2;
    }
    model = !strcmp(argv[1], "8580") ? SID_MOS8580 : SID_MOS6581;
    if (read_trace(argv[2], &w, &nw, &end)) return 1;
    if (sid_tables_init(argv[3])) return 1;
    vec = fopen(argv[4], "w");
    expf = fopen(argv[5], "w");
    if (!vec || !expf) { perror("output"); return 1; }

    fprintf(vec, "; generated by tools/dsp/make_vec.c; do not edit\n");
    fprintf(vec, "cfg_wave_zero equ %d\n", (int)sid_wave_zero(model));
    fprintf(vec, "cfg_ttl_start equ %d\n", (int)sid_floating_ttl_start(model));
    fprintf(vec, "cfg_model equ %d\n", (int)model);
    fprintf(vec, "cfg_sr_start equ %d\n", (int)sid_shift_reset_start(model));
    {
        int32_t cc, mk, fg;
        sid_mix_config(model, &cc, &mk, &fg);
        fprintf(vec, "cfg_hp_cancel equ %d\ncfg_mix_k equ %d\ncfg_filter_gain equ %d\n", (int)cc, (int)mk, (int)fg);
    }
    for (i = 0; i < 16; i++) tmp[i] = sid_tab_rate_period()[i];
    table(vec, "tab_rate", tmp, 16);
    for (i = 0; i < 16; i++) tmp[i] = sid_tab_sustain_level()[i];
    table(vec, "tab_sust", tmp, 16);
    /* The DAC tables as the kernel wants them (protocol.inc): scaled so that one
     * fractional multiply of the two words is the voice output, the wave zero
     * folded in, and the envelope DAC paired with the exponential counter
     * period that starts at each envelope value. */
    for (i = 0; i < 256; i++) {
        int per = 0;
        switch (i) {
        case 0xff: per = 1; break;
        case 0x5d: per = 2; break;
        case 0x36: per = 4; break;
        case 0x1a: per = 8; break;
        case 0x0e: per = 16; break;
        case 0x06: per = 30; break;
        case 0x00: per = -1; break;
        }
        tmp[2 * i] = (unsigned)sid_tab_env_dac(model)[i] << 13;
        tmp[2 * i + 1] = (unsigned)per & 0xffffff;
    }
    table(vec, "tab_env", tmp, 512);
    for (i = 0; i < 4096; i++)
        tmp[i] = (unsigned)(((int)sid_tab_wave_dac(model)[i] - (int)sid_wave_zero(model)) * 1024) & 0xffffff;
    table(vec, "tab_wavedac", tmp, 4096);
    {
        static const int combined[4] = { 3, 5, 6, 7 };
        char label[16];
        int k;
        for (k = 0; k < 4; k++) {
            for (i = 0; i < 4096; i++) tmp[i] = sid_tab_wave(model, combined[k])[i];
            snprintf(label, sizeof label, "tab_wave%d", combined[k]);
            table(vec, label, tmp, 4096);
        }
    }

    /* Run the reference to find the frame each write lands in and the output. */
    sid_ref_reset(&s, model);
    fprintf(vec, "vec_coef0:\n        dc.l    %d,%d,%d,%d\n", (int)s.flt.c.a1, (int)s.flt.c.a2, (int)s.flt.c.a3, (int)s.flt.c.k4);
    {
        size_t cap = nw + 1;
        long *ef = malloc(cap * sizeof *ef);
        sid_filter_coeffs_t *ec = malloc(cap * sizeof *ec);
        for (frame = 1; c < end; frame++) {
            uint32_t peek = s.eps;
            int n = sid_frame_step(&peek);

            while (wi < nw && w[wi].cycle < c + n) {
                sid_ref_write(&s, w[wi].reg, w[wi].value);
                ef[wi] = frame;
                ec[wi] = s.flt.c;               /* the coefficients after this write */
                wi++;
            }
            sid_ref_frame(&s, &fr);
            c += fr.n;
            fprintf(expf, "%d %d %d %d\n", fr.naive[0], fr.naive[1], fr.naive[2], fr.mix);
            nframes++;
        }
        fprintf(vec, "vec_frames equ %ld\n", nframes);
        fprintf(vec, "vec_events:\n");
        for (k = 0; k < nw; k++)
            fprintf(vec, "        dc.l    %ld,%u,%u,%d,%d,%d,%d\n", ef[k], w[k].reg, w[k].value,
                    (int)ec[k].a1, (int)ec[k].a2, (int)ec[k].a3, (int)ec[k].k4);
        fprintf(vec, "        dc.l    -1,0,0,0,0,0,0\n");
        free(ef);
        free(ec);
    }
    fclose(vec);
    fclose(expf);
    free(w);
    return 0;
}
