/*
 * Turn a register trace into a DSP test vector and the expected output.
 *
 *   make_vec <6581|8580> <trace> <resid_dir> <vec.i> <expected.txt>
 *
 * vec.i is an m68k include for tools/dsp/voicetest.s: the tables the DSP needs
 * (rate periods, sustain levels, envelope and wave DAC), the chip constants,
 * the frame count, and the register writes tagged with the frame they are
 * applied before (the same rule as ref_run: a write belongs to the frame whose
 * cycle range contains it). expected.txt has the reference model's voice 0
 * `naive` output, one integer per frame.
 */
#include "sid_ref.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct { long long cycle; unsigned reg, value; } write_t;

static int read_trace(const char *path, write_t **out, size_t *count, long long *end)
{
    FILE *f = fopen(path, "r");
    char line[256];
    size_t cap = 1024, n = 0;
    write_t *w = malloc(cap * sizeof *w);

    *end = 0;
    if (!f) { perror(path); return -1; }
    while (fgets(line, sizeof line, f)) {
        char *p = line;
        long long c;
        int r, v;
        while (*p == ' ' || *p == '\t') ++p;
        if (*p == '#' || *p == '\n' || *p == 0) continue;
        if (!strncmp(p, "end", 3)) { *end = strtoll(p + 3, NULL, 0); continue; }
        if (sscanf(p, "%lli %i %i", &c, &r, &v) == 3) {
            if (n == cap) { cap *= 2; w = realloc(w, cap * sizeof *w); }
            w[n].cycle = c; w[n].reg = (unsigned)r; w[n].value = (unsigned)v;
            n++;
        }
    }
    fclose(f);
    *out = w;
    *count = n;
    return *end > 0 ? 0 : -1;
}

static void table(FILE *f, const char *label, const unsigned *v, int n)
{
    int i;
    fprintf(f, "%s:\n", label);
    for (i = 0; i < n; i += 8) {
        int j;
        fprintf(f, "        dc.l    ");
        for (j = 0; j < 8 && i + j < n; j++)
            fprintf(f, "%s%u", j ? "," : "", v[i + j]);
        fputc('\n', f);
    }
}

int main(int argc, char **argv)
{
    sid_ref_t s;
    sid_frame_t fr;
    write_t *w;
    size_t nw, wi = 0, k;
    long long end, c = 0;
    long nframes = 0;
    sid_model_t model;
    unsigned tmp[4096];
    FILE *vec, *expf;
    int i;
    long frame;

    if (argc < 6) {
        fprintf(stderr, "usage: %s 6581|8580 trace resid_dir vec.i expected.txt\n", argv[0]);
        return 2;
    }
    model = !strcmp(argv[1], "8580") ? SID_MOS8580 : SID_MOS6581;
    if (read_trace(argv[2], &w, &nw, &end)) return 1;
    if (sid_tables_init(argv[3])) return 1;
    vec = fopen(argv[4], "w");
    expf = fopen(argv[5], "w");
    if (!vec || !expf) { perror("output"); return 1; }

    fprintf(vec, "; generated by tools/dsp/make_vec.c; do not edit\n");
    fprintf(vec, "cfg_wave_zero equ %d\n", (int)sid_wave_zero(model));
    fprintf(vec, "cfg_ttl_start equ %d\n", (int)sid_floating_ttl_start(model));
    for (i = 0; i < 16; i++) tmp[i] = sid_tab_rate_period()[i];
    table(vec, "tab_rate", tmp, 16);
    for (i = 0; i < 16; i++) tmp[i] = sid_tab_sustain_level()[i];
    table(vec, "tab_sust", tmp, 16);
    for (i = 0; i < 256; i++) tmp[i] = sid_tab_env_dac(model)[i];
    table(vec, "tab_envdac", tmp, 256);
    for (i = 0; i < 4096; i++) tmp[i] = sid_tab_wave_dac(model)[i];
    table(vec, "tab_wavedac", tmp, 4096);

    /* Run the reference to find the frame each write lands in and the output. */
    sid_ref_reset(&s, model);
    {
        size_t cap = nw + 1;
        long *ef = malloc(cap * sizeof *ef);
        for (frame = 1; c < end; frame++) {
            uint32_t peek = s.eps;
            int n = sid_frame_step(&peek);

            while (wi < nw && w[wi].cycle < c + n) {
                sid_ref_write(&s, w[wi].reg, w[wi].value);
                ef[wi] = frame;
                wi++;
            }
            sid_ref_frame(&s, &fr);
            c += fr.n;
            fprintf(expf, "%d\n", fr.naive[0]);
            nframes++;
        }
        fprintf(vec, "vec_frames equ %ld\n", nframes);
        fprintf(vec, "vec_events:\n");
        for (k = 0; k < nw; k++)
            fprintf(vec, "        dc.l    %ld,%u,%u\n", ef[k], w[k].reg, w[k].value);
        fprintf(vec, "        dc.l    -1,0,0\n");
        free(ef);
    }
    fclose(vec);
    fclose(expf);
    free(w);
    return 0;
}
